package  l2s.Phantoms.enums;

public enum PhantomType
{
	PHANTOM,
	PHANTOM_CLAN_MEMBER,
	PHANTOM_BOT_HUNTER,
	PHANTOM_FISHING,
	PHANTOM_INSTANCES,
	PHANTOM_HARD,
	PHANTOM_CRAFTER,
	PHANTOM_TRADER,
	PHANTOM_TOWNS_PEOPLE,
	PHANTOM_PARTY,
	NONE;

}