package l2s.gameserver.stats

/**
 * @author Sdw
 * @author Java-man
 *
 * @since 12.10.2019
 */
enum class BooleanStat {
    ABNORMAL_SHIELD,
    ATTACK_BEHIND,
    ATTACK_MUTED,
    BETRAYED,
    BLOCK_ACTIONS,
    BLOCK_BUFF,
    BLOCK_CHAT,
    BLOCK_CONTROL,
    BLOCK_DEBUFF,
    BLOCK_ESCAPE,
    BLOCK_MOVE,
    BLOCK_RESURRECTION,
    BLOCK_SPELL,
    CAN_CREATE_COMMAND_CHANNEL,
    CHEAPSHOT,
    CONFUSED,
    /*DISABLE_VITALITY,*/
    DISARMED,
    /*DOUBLE_CAST,
    FACE_OFF,*/
    FAKE_DEATH,
    FEAR,
    /*HEAL_SPECIAL_CRITICAL,*/
    HP_BLOCKED,
    IGNORE_DEATH,
    INVIS_DISABLED,
    /*MAINTAIN_VITALITY,*/
    MP_BLOCKED,
    PHYSICAL_POLEARM_TARGET_SINGLE,
    PHYSICAL_SHIELD_DEFENCE_ANGLE_ALL,
    PHYSICAL_SKILL_MUTED,
    PRESERVE_ABNORMAL,
    /*PROTECT_DEATH_PENALTY,*/
    PROTECTION_BLESSING,
    PRIMARY_AGATHION_SLOT_ENABLED,
    SPECIAL_SKILL_MUTED,
    /*RECHARGE_VITALITY,*/
    RELAX,
    RESURRECTION_SPECIAL,
    /*TARGETING_DISABLE,
    TRANSFORM_DISABLE,*/
    UNTARGETABLE
}