/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * https://github.com/Kotlin/kotlinx.serialization
   */
  const val kotlinx_serialization_runtime: String =
          "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" +
                  Versions.org_jetbrains_kotlinx_kotlinx_serialization

  /**
   * https://github.com/Kotlin/kotlinx.coroutines
   */
  const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
          Versions.org_jetbrains_kotlinx_kotlinx_coroutines

  /**
   * https://logging.apache.org/log4j/2.x/
   */
  const val log4j_api: String = "org.apache.logging.log4j:log4j-api:" +
          Versions.org_apache_logging_log4j

  /**
   * https://logging.apache.org/log4j/2.x/
   */
  const val log4j_core: String = "org.apache.logging.log4j:log4j-core:" +
          Versions.org_apache_logging_log4j

  /**
   * https://logging.apache.org/log4j/2.x/
   */
  const val log4j_slf4j18_impl: String = "org.apache.logging.log4j:log4j-slf4j18-impl:" +
          Versions.org_apache_logging_log4j

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
          Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_scripting_compiler_embeddable: String =
          "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
                  Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:" +
          Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_serialization_unshaded: String =
          "org.jetbrains.kotlin:kotlin-serialization-unshaded:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
          Versions.org_jetbrains_kotlin

  /**
   * https://github.com/google/flogger
   */
  const val flogger: String = "com.google.flogger:flogger:" + Versions.com_google_flogger

  /**
   * https://github.com/google/flogger
   */
  const val flogger_slf4j_backend: String = "com.google.flogger:flogger-slf4j-backend:" +
          Versions.com_google_flogger

  /**
   * https://github.com/google/flogger
   */
  const val flogger_system_backend: String = "com.google.flogger:flogger-system-backend:" +
          Versions.com_google_flogger

  /**
   * https://github.com/google/flogger
   */
  const val google_extensions: String = "com.google.flogger:google-extensions:" +
          Versions.com_google_flogger

  /**
   * http://owner.aeonbits.org
   */
  const val owner_java8: String = "org.aeonbits.owner:owner-java8:" + Versions.org_aeonbits_owner

  const val config: String = "com.typesafe:config:" + Versions.com_typesafe

  /**
   * http://owner.aeonbits.org
   */
  const val owner_java8_extras: String = "org.aeonbits.owner:owner-java8-extras:" +
          Versions.org_aeonbits_owner

  /**
   * https://netty.io/
   */
  const val netty_buffer: String = "io.netty:netty-buffer:" + Versions.io_netty

  /**
   * https://netty.io/
   */
  const val netty_common: String = "io.netty:netty-common:" + Versions.io_netty

  /**
   * https://netty.io/
   */
  const val netty_transport_native_epoll: String = "io.netty:netty-transport-native-epoll:" +
          Versions.io_netty

  const val vertx_core: String = "io.vertx:vertx-core:" + Versions.io_vertx

  const val vertx_lang_kotlin: String = "io.vertx:vertx-lang-kotlin:" + Versions.io_vertx

  /**
   * https://bitbucket.org/trove4j/trove/src/master/
   */
  const val net_sf_trove4j_core: String = "net.sf.trove4j:core:" + Versions.net_sf_trove4j_core

  const val de_fayard_buildsrcversions_gradle_plugin: String =
          "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
                  Versions.de_fayard_buildsrcversions_gradle_plugin

  const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
          "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
                  Versions.org_jetbrains_kotlin_jvm_gradle_plugin

  const val net_ltgt_errorprone_gradle_plugin: String =
          "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:" +
                  Versions.net_ltgt_errorprone_gradle_plugin

  /**
   * https://github.com/cslee00/digitalascent-errorprone-logger
   */
  const val digitalascent_errorprone_flogger: String =
          "com.digitalascent:digitalascent-errorprone-flogger:" +
                  Versions.digitalascent_errorprone_flogger

  /**
   * http://www.eclipse.org/jdt
   */
  const val org_eclipse_jdt_compiler_tool: String =
          "org.eclipse.jdt:org.eclipse.jdt.compiler.tool:" +
                  Versions.org_eclipse_jdt_compiler_tool

  /**
   * http://www.eclipse.org/jdt
   */
  const val org_eclipse_jdt_compiler_apt: String =
          "org.eclipse.jdt:org.eclipse.jdt.compiler.apt:" + Versions.org_eclipse_jdt_compiler_apt

  /**
   * https://commons.apache.org/proper/commons-collections/
   */
  const val commons_collections4: String = "org.apache.commons:commons-collections4:" +
          Versions.commons_collections4

  /**
   * http://velocity.apache.org/engine/devel/
   */
  const val velocity_engine_core: String = "org.apache.velocity:velocity-engine-core:" +
          Versions.velocity_engine_core

  /**
   * https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/
   */
  const val mariadb_java_client: String = "org.mariadb.jdbc:mariadb-java-client:" +
          Versions.mariadb_java_client

  /**
   * https://github.com/albfernandez/juniversalchardet
   */
  const val juniversalchardet: String = "com.github.albfernandez:juniversalchardet:" +
          Versions.juniversalchardet

  const val error_prone_core: String = "com.google.errorprone:error_prone_core:" +
          Versions.error_prone_core

  /**
   * https://github.com/hazendaz/htmlcompressor/
   */
  const val htmlcompressor: String = "com.github.hazendaz:htmlcompressor:" +
          Versions.htmlcompressor

  /**
   * https://commons.apache.org/proper/commons-lang/
   */
  const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

  /**
   * https://github.com/RoaringBitmap/RoaringBitmap
   */
  const val roaringbitmap: String = "org.roaringbitmap:RoaringBitmap:" + Versions.roaringbitmap

  /**
   * https://commons.apache.org/proper/commons-text
   */
  const val commons_text: String = "org.apache.commons:commons-text:" + Versions.commons_text

  /**
   * https://eclipse-ee4j.github.io/jaxb-ri
   */
  const val jaxb_runtime: String = "org.glassfish.jaxb:jaxb-runtime:" + Versions.jaxb_runtime

  /**
   * http://java.sun.com/javase/technologies/desktop/javabeans/jaf/index.jsp
   */
  const val activation: String = "javax.activation:activation:" + Versions.activation

  /**
   * https://commons.apache.org/proper/commons-io/
   */
  const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

  /**
   * http://cron-parser.com/
   */
  const val cron_utils: String = "com.cronutils:cron-utils:" + Versions.cron_utils

  /**
   * http://lmax-exchange.github.com/disruptor
   */
  const val disruptor: String = "com.lmax:disruptor:" + Versions.disruptor

  /**
   * http://jaxb.java.net
   */
  const val jaxb_core: String = "com.sun.xml.bind:jaxb-core:" + Versions.jaxb_core

  /**
   * https://eclipse-ee4j.github.io/jaxb-ri
   */
  const val jaxb_impl: String = "com.sun.xml.bind:jaxb-impl:" + Versions.jaxb_impl

  /**
   * http://www.slf4j.org
   */
  const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.slf4j_api

  /**
   * https://github.com/ben-manes/caffeine
   */
  const val caffeine: String = "com.github.ben-manes.caffeine:caffeine:" + Versions.caffeine

  /**
   * https://github.com/brettwooldridge/HikariCP
   */
  const val hikaricp: String = "com.zaxxer:HikariCP:" + Versions.hikaricp

  /**
   * https://github.com/javaee/jaxb-spec
   */
  const val jaxb_api: String = "javax.xml.bind:jaxb-api:" + Versions.jaxb_api

  const val exposed: String = "org.jetbrains.exposed:exposed:" + Versions.exposed

  /**
   * http://dom4j.github.io/
   */
  const val dom4j: String = "org.dom4j:dom4j:" + Versions.dom4j

  /**
   * https://github.com/google/guava
   */
  const val guava: String = "com.google.guava:guava:" + Versions.guava

  const val javac: String = "com.google.errorprone:javac:" + Versions.javac

  /**
   * http://www.jdom.org
   */
  const val jdom2: String = "org.jdom:jdom2:" + Versions.jdom2

  /**
   * https://github.com/google/gson
   */
  const val gson: String = "com.google.code.gson:gson:" + Versions.gson

  /**
   * https://github.com/charleskorn/kaml
   */
  const val kaml: String = "com.charleskorn.kaml:kaml:" + Versions.kaml
}
